package med.voll.apimed.domain.Medicos;

public enum Especialidade {
    ORTOPEDIA,
    CARDIOLOGIA,
    DERMATOLOGIA,
    PEDIATRIA,
    GINECOLOGIA,
    PSIQUIATRIA,
    CLINICA_GERAL,
    OFTALMOLOGIA,
    OTORRINOLARINGOLOGIA,
    UROLOGIA,
    NEUROLOGIA,
    ENDROCRINOLOGIA,
    GASTROENTEROLOGIA,
    REUMATOLOGIA,
    HEMATOLOGIA,
}
